name: load mets to transcribus
on:
  workflow_dispatch:
jobs:
  download:
    name: create transcribus documents from mets
    runs-on: ubuntu-latest
    env:
      TRANSKRIBUS_USER: ${{secrets.TR_USER}}
      TRANSKRIBUS_PASSWORD: ${{secrets.TR_PW}}
      USER_TOKEN: ${{ secrets.ACTIONS_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python Packages
        run: |
          pip install -r ./scripts/requirements.txt
      - name: trigger base_row_dump_workflow to make shure, dumps are up to date
        run: |
          status=$(curl --request POST \
          --url 'https://api.github.com/repos/bundesverfassung-oesterreich/bv-entities/dispatches' \
          --header "authorization: token $USER_TOKEN" \
          --data '{"event_type": "triggered by transkribus-import-workflow"}')
          if [ -n "$status" ]; then  exit 1; fi
          echo "waiting for 1 minute to make shure all data are getting processed"
          sleep 1m
      - name: ingest goobi-mets to transcribus
        run: |
          python scripts/ingest.py