name: load mets to transcribus
on:
  workflow_dispatch

jobs:
  download:
    name: create transcribus documents from mets
    runs-on: ubuntu-latest
    env:
      TRANSKRIBUS_USER: ${{secrets.TR_USER}}
      TRANSKRIBUS_PASSWORD: ${{secrets.TR_PW}}
    steps:
      - uses: actions/checkout@v3
      - name: Install Python Packages
        run: |
          pip install -r ./scripts/requirements.txt
      - name: ingest goobi-mets to transcribus
        run: |
          python scripts/ingest.py